---
 - name: Update repo and cache
   apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

 - name: Upgrade all packages
   apt: state=latest force_apt_get=yes

 - name: Install Packages
   apt:
     name: "{{ common_packages }}"
     state: present
